---
- name: Downloads Hashicorp's Serf
  get_url: >
    url="{{ install.download_location }}/{{ serf.version }}/serf_{{ serf.version }}_linux_{{ serf.arch }}.zip"
    dest="/tmp/"
    mode=0755
  sudo: no
  tags:
    - hashicorp
    - serf
    - install

- name: Installs Hashicorp's serf
  shell: unzip -u -d {{ install.dir }} /tmp/serf_{{ serf.version }}_linux_{{ serf.arch }}.zip ; chmod 775 {{ install.dir }}/serf; chown root:staff {{ install.dir }}/serf
  sudo: yes

  tags:
    - hashicorp
    - serf
    - install
